SELECT COLUMN_TYPE, COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_SCHEMA = 'zoldify' 
AND TABLE_NAME = 'products' 
AND COLUMN_NAME = 'condition';

SELECT id, name, `condition` FROM products ORDER BY id DESC LIMIT 10;
