-- Thêm cột balance và avatar vào bảng users
-- Đã comment lại vì column đã tồn tại, tránh lỗi Duplicate column
-- ALTER TABLE users 
-- ADD COLUMN balance DECIMAL(15,2) DEFAULT 0.00 AFTER role,
-- ADD COLUMN avatar VARCHAR(255) DEFAULT NULL AFTER balance;
